version: '3.8'

services:
  cheahpdf:
    build: .
    ports:
      - "8002:8002"
    environment:
      - FLASK_ENV=production
      - FLASK_DEBUG=False
      - HOST=0.0.0.0
      - PORT=8002
      - UPLOAD_FOLDER=uploads
      - OUTPUT_FOLDER=outputs
      - MAX_FILE_SIZE=52428800
      - PDF_DPI=600
    volumes:
      - ./uploads:/app/uploads
      - ./outputs:/app/outputs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8002/health"]
      interval: 30s
      timeout: 10s
      retries: 3